version: "3.9"

services:
  printing-app:
    build: .
    container_name: printing-backend
    ports:
      - "8080:8080"

    environment:
      DB_HOST: ep-summer-pond-an2szf6l-pooler.c-6.us-east-1.aws.neon.tech
      DB_PORT: 5432
      DB_NAME: neondb
      DB_USER: neondb_owner
      DB_PASSWORD: npg_8YCOvDXybks2

    restart: always